package com.jai.threadtabs;

import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.widget.*;import android.util.Base64;import com.google.android.gms.auth.api.identity.*;import com.google.android.gms.common.api.Scope;import org.json.*;import java.security.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;

public class AccountsActivity extends Activity {
    private final ExecutorService work=Executors.newSingleThreadExecutor();private TextView status;private boolean busy=false;
    private static final String REDIRECT="com.jai.threadtabs://oauth/outlook";
    private static final String SCOPE="offline_access https://graph.microsoft.com/Mail.Read https://graph.microsoft.com/User.Read";
    @Override public void onCreate(Bundle b){super.onCreate(b);screen();handle(getIntent());}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);handle(i);}
    private void screen(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);l.setPadding(28,72,28,28);ScrollView s=new ScrollView(this);s.addView(l);setContentView(s);TextView title=new TextView(this);title.setText("Gmail + Outlook");title.setTextSize(26);l.addView(title);status=new TextView(this);status.setText("Connect one account per provider. Sync loads the latest 50 Gmail or 100 Outlook messages. Groups and appearance changes stay in Haven Message. Emails refresh here when you tap Sync.");l.addView(status);
        add(l,"Connect / sync Gmail",this::gmail);add(l,"Connect Outlook",this::outlook);add(l,"Sync Outlook",this::syncOutlook);add(l,"Outlook app setup",this::microsoftSetup);add(l,"Provider setup instructions",this::setupHelp);
        for(String provider:new String[]{"gmail","outlook"}){long at=getSharedPreferences("mail",0).getLong(provider+"_synced",0);TextView t=new TextView(this);t.setText(provider+": "+(at==0?"not synced":getSharedPreferences("mail",0).getInt(provider+"_count",0)+" messages · "+java.text.DateFormat.getDateTimeInstance().format(new Date(at))));l.addView(t);add(l,"Disconnect "+provider,()->new AlertDialog.Builder(this).setMessage("Remove this account's cached emails from Haven Message? Your mailbox is unchanged. You can also revoke access in your Google or Microsoft account settings.").setNegativeButton("Cancel",null).setPositiveButton("Disconnect",(d,w)->{if(busy){status.setText("Wait for the current sync to finish, then disconnect.");return;}MailData.clear(this,provider);GroupWidget.snapshot(this,"email",MailData.cached(this),new Store(this,"email"));screen();}).show());}
        add(l,"Close",this::finish);
    }
    private void add(LinearLayout l,String title,Runnable r){Button b=new Button(this);b.setText(title);b.setAllCaps(false);b.setOnClickListener(v->r.run());l.addView(b);}
    private void gmail(){if(busy)return;busy=true;status.setText("Requesting Gmail access…");AuthorizationRequest req=AuthorizationRequest.builder().setRequestedScopes(Collections.singletonList(new Scope("https://www.googleapis.com/auth/gmail.readonly"))).build();
        Identity.getAuthorizationClient(this).authorize(req).addOnSuccessListener(result->{if(isDestroyed())return;if(result.hasResolution())try{startIntentSenderForResult(result.getPendingIntent().getIntentSender(),301,null,0,0,0);}catch(Exception e){fail("Could not open Google consent.");}else acceptGoogle(result);}).addOnFailureListener(e->fail("Google authorization did not complete. Check Google Play services, Gmail API activation, Android OAuth registration and test-user access."));
    }
    private void acceptGoogle(AuthorizationResult result){String token=result.getAccessToken();if(token==null||token.isEmpty()){fail("Google did not grant Gmail read access.");return;}sync("gmail",()->MailData.gmail(token));}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==301){if(result!=RESULT_OK){fail("Gmail connection canceled. Your SMS features still work.");return;}try{acceptGoogle(Identity.getAuthorizationClient(this).getAuthorizationResultFromIntent(data));}catch(Exception e){fail("Google did not grant access. Check provider setup and try again.");}}}
    private void microsoftSetup(){EditText field=new EditText(this);field.setSingleLine();field.setHint("Application (client) ID");field.setText(getSharedPreferences("mail",0).getString("ms_client",""));AlertDialog d=new AlertDialog.Builder(this).setTitle("Outlook app registration").setMessage("Enter your Microsoft public-client application ID. No client secret is needed. Redirect URI: "+REDIRECT).setView(field).setPositiveButton("Save",null).setNegativeButton("Cancel",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String id=field.getText().toString().trim();try{UUID.fromString(id);}catch(Exception e){field.setError("Enter a valid application UUID");return;}getSharedPreferences("mail",0).edit().putString("ms_client",id).apply();d.dismiss();}));d.show();}
    private void outlook(){if(busy)return;String client=getSharedPreferences("mail",0).getString("ms_client","");if(client.isEmpty()){microsoftSetup();return;}try{String verifier=OAuthPolicy.nonce(),state=OAuthPolicy.nonce();SecureStore.put(this,"outlook_pending",new JSONObject().put("verifier",verifier).put("state",state).put("client",client).put("time",System.currentTimeMillis()).toString());String challenge=OAuthPolicy.challenge(verifier);
            String url="https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id="+MailData.enc(client)+"&response_type=code&redirect_uri="+MailData.enc(REDIRECT)+"&response_mode=query&scope="+MailData.enc(SCOPE)+"&state="+state+"&code_challenge="+challenge+"&code_challenge_method=S256&prompt=select_account";startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));
        }catch(Exception e){fail("Could not start Microsoft sign-in. Check that a browser is installed.");}}
    private void handle(Intent intent){Uri u=intent.getData();if(u==null||!"com.jai.threadtabs".equals(u.getScheme())||!"oauth".equals(u.getHost())||!"/outlook".equals(u.getPath()))return;intent.setData(null);if(busy)return;
        try{String raw=SecureStore.get(this,"outlook_pending");if(raw.isEmpty())throw new Exception();JSONObject pending=new JSONObject(raw);String state=u.getQueryParameter("state");if(!OAuthPolicy.valid(state,pending.getString("state"),pending.getLong("time"),System.currentTimeMillis()))throw new Exception();SecureStore.remove(this,"outlook_pending");if(u.getQueryParameter("error")!=null){fail("Microsoft sign-in was canceled or blocked by account policy.");return;}String code=u.getQueryParameter("code");if(code==null)throw new Exception();busy=true;status.setText("Connecting Outlook…");work.execute(()->{try{JSONObject tokens=MailData.http("POST","https://login.microsoftonline.com/common/oauth2/v2.0/token",null,"client_id="+MailData.enc(pending.getString("client"))+"&grant_type=authorization_code&code="+MailData.enc(code)+"&redirect_uri="+MailData.enc(REDIRECT)+"&code_verifier="+MailData.enc(pending.getString("verifier"))+"&scope="+MailData.enc(SCOPE));tokens.put("client",pending.getString("client")).put("expires_at",System.currentTimeMillis()+tokens.optLong("expires_in",3600)*1000);SecureStore.put(this,"outlook",tokens.toString());runOnUiThread(()->{busy=false;syncOutlook();});}catch(Exception e){fail(e.getMessage());}});
        }catch(Exception e){fail("This sign-in link expired or did not match your request. Start Connect Outlook again.");}
    }
    private void syncOutlook(){if(busy)return;sync("outlook",()->{String raw=SecureStore.get(this,"outlook");if(raw.isEmpty())throw new Exception("Connect Outlook first.");JSONObject token=new JSONObject(raw);if(System.currentTimeMillis()+60000>=token.optLong("expires_at")){String refresh=token.optString("refresh_token");if(refresh.isEmpty())throw new Exception("Connect Outlook again to renew access.");JSONObject next=MailData.http("POST","https://login.microsoftonline.com/common/oauth2/v2.0/token",null,"client_id="+MailData.enc(token.getString("client"))+"&grant_type=refresh_token&refresh_token="+MailData.enc(refresh)+"&scope="+MailData.enc(SCOPE));next.put("client",token.getString("client")).put("expires_at",System.currentTimeMillis()+next.optLong("expires_in",3600)*1000);if(!next.has("refresh_token"))next.put("refresh_token",refresh);SecureStore.put(this,"outlook",next.toString());token=next;}return MailData.outlook(token.getString("access_token"));});}
    private interface Fetch{JSONArray get()throws Exception;}
    private void sync(String provider,Fetch fetch){busy=true;status.setText("Syncing "+provider+"… Your existing messages stay available.");work.execute(()->{try{JSONArray data=fetch.get();MailData.save(this,provider,data);runOnUiThread(()->{if(isDestroyed())return;busy=false;GroupWidget.snapshot(this,"email",MailData.cached(this),new Store(this,"email"));screen();status.setText("Synced "+data.length()+" "+provider+" messages. Open Email inbox, or your phone/imported inbox, to group and customize them.");});}catch(Exception e){fail(e.getMessage()==null?"Sync failed. Try again.":e.getMessage());}});}
    private void fail(String message){runOnUiThread(()->{if(isDestroyed())return;busy=false;status.setText(message);});}
    private void setupHelp(){new AlertDialog.Builder(this).setTitle("One-time provider setup").setMessage("Gmail: enable Gmail API in your Google Cloud project, configure consent and test users, and register an Android OAuth client for com.jai.threadtabs with this build’s SHA-1 certificate (included in EMAIL-SETUP.md). Google Play services must be installed.\n\nOutlook: register a Microsoft public-client app for personal and organizational accounts. Add the redirect URI "+REDIRECT+" and delegated Mail.Read and User.Read permissions. Enter its application ID using Outlook app setup. A work account may require administrator approval.\n\nNo password or client secret is entered into Haven Message. The included EMAIL-SETUP.md has the full steps.").setPositiveButton("OK",null).show();}
    @Override protected void onDestroy(){work.shutdownNow();super.onDestroy();}
}
