package com.jai.threadtabs;
import android.app.*;import android.appwidget.*;import android.content.*;import android.graphics.Color;import android.widget.*;import org.json.*;import java.util.*;
public class GroupWidget extends AppWidgetProvider {
    static void snapshot(Context c,String mode,List<SmsData.Message> messages,Store store){JSONArray a=new JSONArray();Set<String> seen=new HashSet<>();for(SmsData.Message m:messages){String group=store.resolve(m);String key=group+"|"+m.thread;if(!seen.add(key))continue;try{a.put(new JSONObject().put("thread",m.thread).put("name",m.name).put("body",m.body).put("group",group).put("source",m.source));}catch(Exception ignored){}if(a.length()>=500)break;}c.getSharedPreferences("widgets",0).edit().putString("snapshot_"+mode,a.toString()).putLong("updated_"+mode,System.currentTimeMillis()).apply();updateAll(c);}
    static void updateAll(Context c){AppWidgetManager m=AppWidgetManager.getInstance(c);for(int id:m.getAppWidgetIds(new ComponentName(c,GroupWidget.class)))update(c,m,id);}
    @Override public void onUpdate(Context c,AppWidgetManager manager,int[] ids){for(int id:ids)update(c,manager,id);}
    @Override public void onAppWidgetOptionsChanged(Context c,AppWidgetManager m,int id,android.os.Bundle options){update(c,m,id);}
    @Override public void onDeleted(Context c,int[] ids){for(int id:ids)c.getSharedPreferences("widget_"+id,0).edit().clear().apply();}
    static void update(Context c,AppWidgetManager manager,int id){
        SharedPreferences p=c.getSharedPreferences("widget_"+id,0);String mode=p.getString("mode","demo"),group=p.getString("group","all");Store store=new Store(c,mode);if(!group.equals("all")&&!store.ids().contains(group))group="all";
        RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.group_widget);v.setTextViewText(R.id.widget_title,group.equals("all")?"Haven Message · All":store.group(group).label());v.setInt(R.id.widget_root,"setBackgroundColor",Color.parseColor(p.getString("color","#24223B")));
        long updated=c.getSharedPreferences("widgets",0).getLong("updated_"+mode,0);v.setTextViewText(R.id.widget_hint,(mode.equals("demo")?"Samples · ":"")+(updated==0?"Open app to load messages":"Updated "+android.text.format.DateFormat.format("MMM d, h:mm a",updated))+" · Tap title to refresh");
        v.setOnClickPendingIntent(R.id.widget_title,open(c,id,"",mode,group));v.setOnClickPendingIntent(R.id.widget_hint,PendingIntent.getActivity(c,id,new Intent(c,WidgetConfigActivity.class).putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,id),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));
        JSONArray a;try{a=new JSONArray(c.getSharedPreferences("widgets",0).getString("snapshot_"+mode,"[]"));}catch(Exception e){a=new JSONArray();}
        int[] rows={R.id.widget_row1,R.id.widget_row2,R.id.widget_row3,R.id.widget_row4};int n=0;Set<String> seen=new HashSet<>();for(int i=0;i<a.length()&&n<4;i++){JSONObject r=a.optJSONObject(i);if(!group.equals("all")&&!group.equals(r.optString("group")))continue;if(!seen.add(r.optString("thread")))continue;v.setTextViewText(rows[n],r.optString("name")+"\n"+(p.getBoolean("preview",false)?r.optString("body"):"Message preview hidden"));v.setOnClickPendingIntent(rows[n],open(c,id,r.optString("thread"),mode,group));n++;}while(n<4){v.setTextViewText(rows[n],n==0?"No messages yet. Open Haven Message to refresh.":"");v.setOnClickPendingIntent(rows[n],open(c,id,"",mode,group));n++;}manager.updateAppWidget(id,v);
    }
    private static PendingIntent open(Context c,int id,String thread,String mode,String group){Intent i=new Intent(c,MainActivity.class).setAction("widget-"+id+"-"+thread).putExtra("open_mode",mode).putExtra("open_thread",thread).putExtra("open_group",group);return PendingIntent.getActivity(c,0,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
}
