package com.jai.threadtabs;
import android.content.Context;import android.text.Html;import android.util.Base64;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Instant;import java.util.*;

final class MailData {
    static JSONObject http(String method,String url,String token,String form)throws Exception{
        HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setInstanceFollowRedirects(false);c.setRequestMethod(method);c.setConnectTimeout(20000);c.setReadTimeout(30000);c.setRequestProperty("Accept","application/json");if(token!=null)c.setRequestProperty("Authorization","Bearer "+token);c.setRequestProperty("Prefer","outlook.body-content-type=\"text\", IdType=\"ImmutableId\"");
        try{if(form!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/x-www-form-urlencoded");try(OutputStream out=c.getOutputStream()){out.write(form.getBytes(StandardCharsets.UTF_8));}}
            int status=c.getResponseCode();InputStream input=status>=400?c.getErrorStream():c.getInputStream();if(input==null)throw new IOException("Provider returned HTTP "+status);ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=input){byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1){if(out.size()+n>8*1024*1024)throw new IOException("Provider response is too large.");out.write(buffer,0,n);}}
            JSONObject result=new JSONObject(out.toString("UTF-8"));if(status<200||status>=300){if(status==401)throw new IOException("Sign-in expired. Connect this account again.");if(status==403)throw new IOException("The provider blocked mailbox access. Check app registration, consent and account policy.");if(status==429)throw new IOException("The provider is busy. Wait a few minutes and refresh.");throw new IOException("Mail service returned HTTP "+status+". Check account setup and try again.");}return result;
        }finally{c.disconnect();}
    }
    static String limit(String text){return text.length()>32000?text.substring(0,32000)+"\n\n[Open this email to read the rest.]":text;}
    static String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(Exception e){throw new IllegalArgumentException(e);}}
    static String address(String from){int l=from.lastIndexOf('<'),r=from.lastIndexOf('>');return l>=0&&r>l?from.substring(l+1,r).trim():from.trim();}
    static String header(JSONObject payload,String name){JSONArray h=payload.optJSONArray("headers");if(h!=null)for(int i=0;i<h.length();i++){JSONObject x=h.optJSONObject(i);if(name.equalsIgnoreCase(x.optString("name")))return x.optString("value");}return "";}
    static String decode(String data){try{return new String(Base64.decode(data,Base64.URL_SAFE|Base64.NO_WRAP),StandardCharsets.UTF_8);}catch(Exception e){return "";}}
    static String plain(JSONObject p){
        String mime=p.optString("mimeType");JSONObject b=p.optJSONObject("body");String body=b==null?"":decode(b.optString("data"));if(mime.equals("text/plain"))return body;if(mime.equals("text/html"))return Html.fromHtml(body,Html.FROM_HTML_MODE_LEGACY).toString();
        JSONArray parts=p.optJSONArray("parts");if(parts!=null){for(int i=0;i<parts.length();i++){JSONObject part=parts.optJSONObject(i);if(part.optString("mimeType").equals("text/plain"))return plain(part);}for(int i=0;i<parts.length();i++){String text=plain(parts.optJSONObject(i));if(!text.isEmpty())return text;}}return "";
    }
    static JSONArray gmail(String token)throws Exception{
        String root="https://gmail.googleapis.com/gmail/v1/users/me";JSONObject profile=http("GET",root+"/profile",token,null);String account=profile.getString("emailAddress");JSONObject page=http("GET",root+"/messages?maxResults=50",token,null);JSONArray ids=page.optJSONArray("messages"),out=new JSONArray();if(ids==null)return out;
        for(int i=0;i<ids.length();i++){if(Thread.currentThread().isInterrupted())throw new IOException("Sync canceled.");JSONObject m=http("GET",root+"/messages/"+enc(ids.getJSONObject(i).getString("id"))+"?format=full",token,null);JSONObject p=m.getJSONObject("payload");String from=header(p,"From"),subject=header(p,"Subject"),body=plain(p);boolean sent=false;JSONArray labels=m.optJSONArray("labelIds");if(labels!=null)for(int j=0;j<labels.length();j++)if(labels.optString(j).equals("SENT"))sent=true;String correspondent=sent?header(p,"To"):from;
            out.put(new JSONObject().put("id",m.getString("id")).put("thread","gmail-"+account+"-"+m.getString("threadId")).put("address",address(correspondent)).put("name",correspondent).put("body",subject+"\n\n"+limit(body.isEmpty()?Html.fromHtml(m.optString("snippet"),0).toString():body)).put("date",m.optLong("internalDate")).put("sent",sent).put("source","Gmail").put("account",account).put("subject",subject).put("web","https://mail.google.com/mail/u/"+UriPath(account)+"/#all/"+m.getString("threadId")));
        }return out;
    }
    private static String UriPath(String s){return android.net.Uri.encode(s);}
    static JSONArray outlook(String token)throws Exception{
        JSONObject user=http("GET","https://graph.microsoft.com/v1.0/me?$select=id,mail,userPrincipalName",token,null);String account=user.optString("mail","");if(account.isEmpty()||account.equals("null"))account=user.optString("userPrincipalName");String accountId=user.getString("id");
        JSONObject page=http("GET","https://graph.microsoft.com/v1.0/me/messages?$top=100&$orderby=receivedDateTime%20desc&$select=id,conversationId,subject,body,from,toRecipients,receivedDateTime,webLink,isDraft",token,null);JSONArray values=page.getJSONArray("value"),out=new JSONArray();
        for(int i=0;i<values.length();i++){JSONObject m=values.getJSONObject(i);if(m.optBoolean("isDraft"))continue;JSONObject from=m.optJSONObject("from");JSONObject addr=from==null?new JSONObject():from.optJSONObject("emailAddress");if(addr==null)addr=new JSONObject();boolean sent=addr.optString("address").equalsIgnoreCase(account);if(sent){JSONArray to=m.optJSONArray("toRecipients");if(to!=null&&to.length()>0)addr=to.getJSONObject(0).getJSONObject("emailAddress");}
            JSONObject b=m.optJSONObject("body");String body=b==null?"":b.optString("content");if(b!=null&&b.optString("contentType").equalsIgnoreCase("html"))body=Html.fromHtml(body,0).toString();long date;try{date=Instant.parse(m.getString("receivedDateTime")).toEpochMilli();}catch(Exception e){date=0;}
            out.put(new JSONObject().put("id",m.getString("id")).put("thread","outlook-"+accountId+"-"+m.optString("conversationId",m.getString("id"))).put("address",addr.optString("address")).put("name",addr.optString("name",addr.optString("address"))).put("body",m.optString("subject")+"\n\n"+limit(body)).put("date",date).put("sent",sent).put("source","Outlook").put("account",account).put("subject",m.optString("subject")).put("web",m.optString("webLink")));
        }return out;
    }
    static synchronized void save(Context c,String provider,JSONArray a)throws Exception{android.util.AtomicFile f=new android.util.AtomicFile(new File(c.getFilesDir(),provider+"-mail.json"));FileOutputStream out=null;try{out=f.startWrite();out.write(a.toString().getBytes(StandardCharsets.UTF_8));f.finishWrite(out);c.getSharedPreferences("mail",0).edit().putLong(provider+"_synced",System.currentTimeMillis()).putInt(provider+"_count",a.length()).apply();}catch(Exception e){if(out!=null)f.failWrite(out);throw e;}}
    static synchronized List<SmsData.Message> cached(Context c){List<SmsData.Message> out=new ArrayList<>();for(String provider:new String[]{"gmail","outlook"})try{android.util.AtomicFile f=new android.util.AtomicFile(new File(c.getFilesDir(),provider+"-mail.json"));JSONArray a=new JSONArray(new String(f.readFully(),StandardCharsets.UTF_8));for(int i=0;i<a.length();i++){JSONObject m=a.getJSONObject(i);SmsData.Message msg=new SmsData.Message(m.getString("id"),m.getString("thread"),m.getString("address"),m.getString("name"),m.getString("body"),m.getLong("date"),m.getBoolean("sent"));msg.source=m.optString("source");msg.account=m.optString("account");msg.subject=m.optString("subject");msg.web=m.optString("web");out.add(msg);}}catch(Exception ignored){}return out;}
    static synchronized void clear(Context c,String provider){new android.util.AtomicFile(new File(c.getFilesDir(),provider+"-mail.json")).delete();SecureStore.remove(c,provider);SecureStore.remove(c,provider+"_pending");
        android.content.SharedPreferences widgets=c.getSharedPreferences("widgets",0);
        for(String mode:new String[]{"live","import","email"})try{JSONArray old=new JSONArray(widgets.getString("snapshot_"+mode,"[]")),clean=new JSONArray();for(int i=0;i<old.length();i++)if(!old.getJSONObject(i).optString("source").equalsIgnoreCase(provider))clean.put(old.getJSONObject(i));widgets.edit().putString("snapshot_"+mode,clean.toString()).apply();}catch(Exception ignored){}
        GroupWidget.updateAll(c);c.getSharedPreferences("mail",0).edit().remove(provider+"_synced").remove(provider+"_count").apply();}
}
