package com.jai.threadtabs;
import android.content.Context;import android.security.keystore.*;import android.util.Base64;import javax.crypto.*;import javax.crypto.spec.GCMParameterSpec;import java.security.KeyStore;import java.nio.charset.StandardCharsets;
/** Provider credentials are encrypted with a non-exportable Android Keystore key. */
final class SecureStore {
    private static javax.crypto.SecretKey key() throws Exception{KeyStore store=KeyStore.getInstance("AndroidKeyStore");store.load(null);if(!store.containsAlias("threadtabs-mail")){KeyGenerator g=KeyGenerator.getInstance("AES","AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder("threadtabs-mail",KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());g.generateKey();}return (javax.crypto.SecretKey)store.getKey("threadtabs-mail",null);}
    static void put(Context c,String name,String value)throws Exception{Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.ENCRYPT_MODE,key());String encoded=Base64.encodeToString(cipher.getIV(),Base64.NO_WRAP)+":"+Base64.encodeToString(cipher.doFinal(value.getBytes(StandardCharsets.UTF_8)),Base64.NO_WRAP);c.getSharedPreferences("credentials",0).edit().putString(name,encoded).commit();}
    static String get(Context c,String name)throws Exception{String raw=c.getSharedPreferences("credentials",0).getString(name,"");if(raw.isEmpty())return "";String[] p=raw.split(":",2);Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.DECRYPT_MODE,key(),new GCMParameterSpec(128,Base64.decode(p[0],Base64.NO_WRAP)));return new String(cipher.doFinal(Base64.decode(p[1],Base64.NO_WRAP)),StandardCharsets.UTF_8);}
    static void remove(Context c,String name){c.getSharedPreferences("credentials",0).edit().remove(name).commit();}
}
