package com.jai.threadtabs;

import android.app.*;import android.content.*;import android.graphics.*;import android.media.MediaMetadataRetriever;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;import java.util.concurrent.*;

public class StyleActivity extends Activity {
    private JSONObject style;private String mode,id;private LinearLayout form;private FrameLayout preview;private EditText bubble,color;private Spinner font,weight;private SeekBar size,dim,radius;private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    @Override public void onCreate(Bundle state){if(getSharedPreferences("settings",0).getBoolean("dark",false))setTheme(R.style.AppThemeDark);super.onCreate(state);mode=getIntent().getStringExtra("mode");id=getIntent().getStringExtra("id");style=Appearance.get(this,mode,id);if(state!=null)try{style=new JSONObject(state.getString("draft",style.toString()));}catch(Exception ignored){}
        ScrollView scroll=new ScrollView(this);form=new LinearLayout(this);form.setOrientation(1);form.setPadding(dp(20),dp(24),dp(20),dp(24));scroll.addView(form);setContentView(scroll);if(Build.VERSION.SDK_INT>=30)scroll.setOnApplyWindowInsetsListener((v,in)->{Insets b=in.getInsets(WindowInsets.Type.systemBars());v.setPadding(b.left,b.top,b.right,b.bottom);return in;});
        label("Make this message yours",24);label("Only this message changes. Your original text stays untouched.",14);preview=new FrameLayout(this);form.addView(preview,new LinearLayout.LayoutParams(-1,dp(160)));
        bubble=field("Bubble color · #RRGGBB",style.optString("bubble","#635BDB"));color=field("Text color · #RRGGBB",style.optString("text","#FFFFFF"));
        label("Quick bubble colors",14);LinearLayout palette=new LinearLayout(this);for(String hex:new String[]{"#635BDB","#C54C76","#25776D","#2465B3","#AD6410","#252535"}){Button b=new Button(this);b.setBackgroundColor(Color.parseColor(hex));b.setContentDescription(hex);b.setOnClickListener(v->bubble.setText(hex));palette.addView(b,new LinearLayout.LayoutParams(0,dp(42),1));}form.addView(palette);
        font=spinner("Font",Appearance.FONTS);for(int i=0;i<Appearance.FONTS.length;i++)if(Appearance.FONTS[i].equals(style.optString("font",getSharedPreferences("settings",0).getString("font","sans-serif"))))font.setSelection(i);
        weight=spinner("Style",new String[]{"Regular","Bold","Italic","Bold italic"});weight.setSelection(style.optInt("weight",0));
        size=slider("Text size (12–32 sp)",20,Math.max(0,style.optInt("size",16)-12));radius=slider("Bubble corners",40,style.optInt("radius",18));dim=slider("Darken background (0–90%)",90,style.optInt("dim",50));
        add("Choose photo background",()->pick("image/*",201));add("Choose video background (up to 30 seconds)",()->pick("video/*",202));add("Remove background",()->{style.remove("media");style.remove("kind");showPreview();});
        add("Import font (.ttf / .otf)",()->pick("*/*",203));add("Use built-in font",()->{style.remove("fontPath");showPreview();});
        add("Preview changes",()->{if(readFields())showPreview();});add("Save appearance",()->{if(readFields()){Appearance.save(this,mode,id,style);setResult(RESULT_OK);finish();}});
        add("Reset this message",()->new AlertDialog.Builder(this).setMessage("Remove this message’s custom colors, font and background?").setNegativeButton("Cancel",null).setPositiveButton("Reset",(d,w)->{Appearance.save(this,mode,id,new JSONObject());setResult(RESULT_OK);finish();}).show());add("Cancel",this::finish);showPreview();
    }
    private void label(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setPadding(0,dp(8),0,dp(4));form.addView(t);}
    private EditText field(String label,String value){label(label,14);EditText e=new EditText(this);e.setSingleLine();e.setText(value);form.addView(e);return e;}
    private Spinner spinner(String title,String[] names){label(title,14);Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));form.addView(s);return s;}
    private SeekBar slider(String title,int max,int value){label(title,14);SeekBar s=new SeekBar(this);s.setMax(max);s.setProgress(value);form.addView(s);return s;}
    private void add(String title,Runnable r){Button b=new Button(this);b.setText(title);b.setAllCaps(false);b.setOnClickListener(v->r.run());form.addView(b);}
    private boolean readFields(){try{String b=bubble.getText().toString().trim(),t=color.getText().toString().trim();if(!b.matches("#[A-Fa-f0-9]{6}")){bubble.setError("Use #RRGGBB");return false;}if(!t.matches("#[A-Fa-f0-9]{6}")){color.setError("Use #RRGGBB");return false;}style.put("bubble",b).put("text",t).put("font",Appearance.FONTS[font.getSelectedItemPosition()]).put("weight",weight.getSelectedItemPosition()).put("size",size.getProgress()+12).put("radius",radius.getProgress()).put("dim",dim.getProgress());return true;}catch(Exception e){return false;}}
    private void showPreview(){preview.removeAllViews();BubbleFrame frame=new BubbleFrame(this,style,0xFF635BDB,true);TextView text=new TextView(this);text.setText(getIntent().getStringExtra("body"));text.setMaxLines(5);text.setTextSize(style.optInt("size",16));text.setTextColor(Appearance.color(style,"text",Color.WHITE));text.setTypeface(Appearance.font(this,style));text.setPadding(dp(16),dp(12),dp(16),dp(12));frame.addView(text,new FrameLayout.LayoutParams(-1,-1));preview.addView(frame,new FrameLayout.LayoutParams(-1,-1));}
    private void pick(String type,int request){readFields();startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType(type).addCategory(Intent.CATEGORY_OPENABLE),request);}
    @Override protected void onSaveInstanceState(Bundle out){readFields();out.putString("draft",style.toString());super.onSaveInstanceState(out);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();ProgressDialog dialog=ProgressDialog.show(this,"Adding background","Preparing your file…",true,false);
        worker.execute(()->{File dest=null;String problem=null;try{File dir=new File(getFilesDir(),"message-media");dir.mkdirs();dest=new File(dir,UUID.randomUUID()+ (req==201?".jpg":req==202?".video":".font"));File raw=new File(dir,UUID.randomUUID()+".tmp");try{
            try(InputStream in=getContentResolver().openInputStream(uri);OutputStream out=new FileOutputStream(raw)){if(in==null)throw new IOException();byte[] buf=new byte[16384];long count=0;int n;while((n=in.read(buf))!=-1){count+=n;if(count>(req==203?5L:40L)*1024*1024)throw new IOException("File is too large (40 MB media / 5 MB fonts).");out.write(buf,0,n);}}
            if(req==201){BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeFile(raw.getPath(),o);if(o.outWidth<1)throw new IOException("That file is not a supported image.");o.inJustDecodeBounds=false;o.inSampleSize=1;while(Math.max(o.outWidth,o.outHeight)/o.inSampleSize>1440)o.inSampleSize*=2;Bitmap b=BitmapFactory.decodeFile(raw.getPath(),o);if(b==null)throw new IOException("Image could not be read.");
                try{int orientation=new android.media.ExifInterface(raw.getPath()).getAttributeInt(android.media.ExifInterface.TAG_ORIENTATION,1);Matrix transform=new Matrix();switch(orientation){case 2:transform.setScale(-1,1);break;case 3:transform.setRotate(180);break;case 4:transform.setScale(1,-1);break;case 5:transform.setRotate(90);transform.postScale(-1,1);break;case 6:transform.setRotate(90);break;case 7:transform.setRotate(-90);transform.postScale(-1,1);break;case 8:transform.setRotate(-90);break;}if(!transform.isIdentity()){Bitmap rotated=Bitmap.createBitmap(b,0,0,b.getWidth(),b.getHeight(),transform,true);if(rotated!=b)b.recycle();b=rotated;}}catch(Exception ignored){}
                try(OutputStream out=new FileOutputStream(dest)){b.compress(Bitmap.CompressFormat.JPEG,90,out);}b.recycle();}
            else if(req==202){MediaMetadataRetriever mr=new MediaMetadataRetriever();try{mr.setDataSource(raw.getPath());long duration=Long.parseLong(mr.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION));if(duration>30000)throw new IOException("Choose a video that is 30 seconds or shorter.");Bitmap b=mr.getFrameAtTime(0);if(b==null)throw new IOException("Video has no readable picture.");try(OutputStream out=new FileOutputStream(dest.getPath()+".jpg")){b.compress(Bitmap.CompressFormat.JPEG,85,out);}b.recycle();if(!raw.renameTo(dest))throw new IOException("Cannot save video.");}finally{mr.release();}}
            else{Typeface.createFromFile(raw);if(!raw.renameTo(dest))throw new IOException("Cannot save font.");}
        }finally{raw.delete();}}catch(Exception e){problem=e.getMessage()==null?"Could not read that file.":e.getMessage();if(dest!=null){dest.delete();new File(dest.getPath()+".jpg").delete();}}
        final File file=dest;final String err=problem;runOnUiThread(()->{if(isDestroyed())return;dialog.dismiss();if(err!=null){new AlertDialog.Builder(this).setMessage(err).setPositiveButton("OK",null).show();return;}try{if(req==203)style.put("fontPath",file.getPath());else style.put("media",file.getPath()).put("kind",req==201?"image":"video");showPreview();}catch(Exception ignored){}});});
    }
    @Override protected void onPause(){super.onPause();preview.removeAllViews();}
    @Override protected void onResume(){super.onResume();if(preview!=null)showPreview();}
    @Override protected void onDestroy(){worker.shutdownNow();super.onDestroy();}
}
