package com.jai.threadtabs;
import android.app.*;import android.appwidget.*;import android.content.*;import android.os.*;import android.widget.*;import java.util.*;
public class WidgetConfigActivity extends Activity {
    private int id;private Spinner source,group;private Store store;
    @Override public void onCreate(Bundle b){super.onCreate(b);id=getIntent().getIntExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,AppWidgetManager.INVALID_APPWIDGET_ID);setResult(RESULT_CANCELED);if(id==AppWidgetManager.INVALID_APPWIDGET_ID){finish();return;}android.appwidget.AppWidgetProviderInfo info=AppWidgetManager.getInstance(this).getAppWidgetInfo(id);if(info==null||!new android.content.ComponentName(this,GroupWidget.class).equals(info.provider)){finish();return;}
        SharedPreferences p=getSharedPreferences("widget_"+id,0);LinearLayout l=new LinearLayout(this);l.setOrientation(1);l.setPadding(32,80,32,24);TextView title=new TextView(this);title.setText("Your Haven Message widget");title.setTextSize(24);l.addView(title);source=new Spinner(this);source.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Sample messages","Phone SMS + email","Imported SMS + email","Email only"}));l.addView(source);group=new Spinner(this);l.addView(group);String[] modes={"demo","live","import","email"};source.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> v){}public void onItemSelected(android.widget.AdapterView<?> v,android.view.View view,int pos,long row){store=new Store(WidgetConfigActivity.this,modes[pos]);List<String> names=new ArrayList<>();names.add("All groups");for(Store.Group g:store.groups)names.add(g.label());group.setAdapter(new ArrayAdapter<>(WidgetConfigActivity.this,android.R.layout.simple_spinner_dropdown_item,names));for(int j=0;j<store.groups.size();j++)if(store.groups.get(j).id.equals(p.getString("group","all")))group.setSelection(j+1);}});for(int i=0;i<modes.length;i++)if(modes[i].equals(p.getString("mode","demo")))source.setSelection(i);
        CheckBox previews=new CheckBox(this);previews.setText("Show message previews on home screen");previews.setChecked(p.getBoolean("preview",false));l.addView(previews);EditText color=new EditText(this);color.setSingleLine();color.setHint("Background color #RRGGBB");color.setText(p.getString("color","#24223B"));l.addView(color);Button save=new Button(this);save.setText("Save widget");l.addView(save);save.setOnClickListener(v->{String hex=color.getText().toString().trim();if(!hex.matches("#[A-Fa-f0-9]{6}")){color.setError("Use #RRGGBB");return;}if(store==null)return;p.edit().putString("mode",modes[source.getSelectedItemPosition()]).putString("group",group.getSelectedItemPosition()==0?"all":store.groups.get(group.getSelectedItemPosition()-1).id).putBoolean("preview",previews.isChecked()).putString("color",hex).apply();GroupWidget.update(this,AppWidgetManager.getInstance(this),id);setResult(RESULT_OK,new Intent().putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,id));finish();});setContentView(l);
    }
}
